jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 1: Authenticate using service account JSON
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      # Step 2: Setup gcloud CLI (already authenticated)
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: sadak-sathi-3ab73
          version: '426.0.0'

      # Step 3: Use gcloud commands
      - name: List GCP projects (example)
        run: gcloud projects list

      # Step 4: Deploy to Firebase
      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --project sadak-sathi-3ab73
