name: Deploy Sadak-Sathi Firebase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4️⃣ Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install

      # 5️⃣ Install functions dependencies
      - name: Install Firebase Functions dependencies
        working-directory: functions
        run: npm install

      # 6️⃣ Setup Firebase Service Account
      - name: Setup Firebase Service Account
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > "${GITHUB_WORKSPACE}/service-account.json"
          export GOOGLE_APPLICATION_CREDENTIALS="${GITHUB_WORKSPACE}/service-account.json"

      # 7️⃣ Build frontend
      - name: Build frontend
        run: npm run build

      # 8️⃣ Deploy frontend hosting
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project sadak-sathi-3ab73

      # 9️⃣ Deploy Firebase Functions
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project sadak-sathi-3ab73
