name: Deploy Firebase (Functions + Hosting)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4️⃣ Authenticate Firebase using Service Account
      - name: Authenticate Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${GITHUB_WORKSPACE}/service-account.json"
          gcloud auth activate-service-account --key-file="${GITHUB_WORKSPACE}/service-account.json"
          gcloud config set project ${{ secrets.VITE_FIREBASE_PROJECT_ID }}

      # 5️⃣ Install dependencies for functions
      - name: Install dependencies
        working-directory: functions
        run: npm install

      # 6️⃣ Deploy Firebase Functions
      - name: Deploy Functions
        run: |
          firebase deploy --only functions --project ${{ secrets.VITE_FIREBASE_PROJECT_ID }} --token "$(gcloud auth print-access-token)"

      # 7️⃣ Deploy Hosting if firebase.json exists
      - name: Deploy Hosting
        run: |
          if [ -f "firebase.json" ]; then
            firebase deploy --only hosting --project ${{ secrets.VITE_FIREBASE_PROJECT_ID }} --token "$(gcloud auth print-access-token)"
          else
            echo "No firebase.json found, skipping hosting deployment."
          fi
