name: Deploy Firebase (Functions + Hosting)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install Firebase CLI & gcloud
      - name: Install Firebase CLI and gcloud
        run: |
          npm install -g firebase-tools
          curl https://sdk.cloud.google.com | bash > /dev/null;
          source $HOME/google-cloud-sdk/path.bash.inc
          gcloud --version

      # 4️⃣ Decode Service Account & Authenticate
      - name: Authenticate Firebase / gcloud
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > "${GITHUB_WORKSPACE}/service-account.json"
          gcloud auth activate-service-account --key-file="${GITHUB_WORKSPACE}/service-account.json"
          gcloud config set project ${{ secrets.VITE_FIREBASE_PROJECT_ID }}

      # 5️⃣ Install dependencies for functions
      - name: Install dependencies
        working-directory: functions
        run: npm install

      # 6️⃣ Deploy Firebase Functions
      - name: Deploy Functions
        run: firebase deploy --only functions --project ${{ secrets.VITE_FIREBASE_PROJECT_ID }}

      # 7️⃣ Deploy Hosting if firebase.json exists
      - name: Deploy Hosting
        run: |
          if [ -f "firebase.json" ]; then
            firebase deploy --only hosting --project ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          else
            echo "No firebase.json found, skipping hosting deployment."
          fi
