name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Save service account JSON from GitHub secret
      - name: Save service account JSON
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" > service-account.json

      # Convert literal \n into actual newlines
      - name: Fix newlines in private key
        run: |
          sed -i 's/\\n/\n/g' service-account.json

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account.json

      - name: Set GCP project
        run: gcloud config set project sadak-sathi-3ab73

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only functions --project sadak-sathi-3ab73
