name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        working-directory: functions
        run: npm install

      # Authenticate to GCP using Service Account Key
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set Firebase project (optional if project already set in firebase.json)
      - name: Set Firebase Project
        run: firebase use --add ${{ secrets.VITE_FIREBASE_PROJECT_ID }}

      # Deploy Cloud Functions
      - name: Deploy Firebase Functions
        env:
          # Main backend keys
          VITE_DHM_API_KEY: ${{ secrets.VITE_DHM_API_KEY }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
          VITE_MAPBOX_API_KEY: ${{ secrets.VITE_MAPBOX_API_KEY }}
          VITE_OPENROUTER_API_KEY: ${{ secrets.VITE_OPENROUTER_API_KEY }}
          VITE_OPENWEATHER_API_KEY: ${{ secrets.VITE_OPENWEATHER_API_KEY }}
          VITE_PUSHER_KEY: ${{ secrets.VITE_PUSHER_KEY }}
          VITE_WAZE_API_KEY: ${{ secrets.VITE_WAZE_API_KEY }}
          VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}

          # Other 3rd-party keys
          VITE_OTHER_3RD_PARTY_KEY: ${{ secrets.VITE_OTHER_3RD_PARTY_KEY }}
          VITE_3RD_PARTY_1: ${{ secrets.VITE_3RD_PARTY_1 }}
          VITE_3RD_PARTY_2: ${{ secrets.VITE_3RD_PARTY_2 }}
          VITE_3RD_PARTY_3: ${{ secrets.VITE_3RD_PARTY_3 }}
          VITE_3RD_PARTY_4: ${{ secrets.VITE_3RD_PARTY_4 }}
          VITE_3RD_PARTY_5: ${{ secrets.VITE_3RD_PARTY_5 }}

        run: |
          cd functions
          firebase deploy --only functions --project ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
