name: Firebase Multi-Env Deploy with Hosting Targets

on:
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      # Step 3: Setup gcloud CLI
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: sadak-sathi-3ab73
          version: '426.0.0'

      # Step 4: Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 5: Determine environment and hosting target
      - name: Set environment
        id: env
        run: |
          if [ "${GITHUB_REF_NAME}" == "main" ]; then
            echo "project=sadak-sathi-prod" >> $GITHUB_ENV
            echo "target=prod-hosting" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" == "staging" ]; then
            echo "project=sadak-sathi-staging" >> $GITHUB_ENV
            echo "target=staging-hosting" >> $GITHUB_ENV
          else
            echo "project=sadak-sathi-dev" >> $GITHUB_ENV
            echo "target=dev-hosting" >> $GITHUB_ENV
          fi

      # Step 6: Deploy to the correct hosting target
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting:${{ env.target }} --project ${{ env.project }}
