name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4️⃣ Write service account key
      - name: Setup Firebase Service Account
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ${GITHUB_WORKSPACE}/service-account.json

      # 5️⃣ Install dependencies (for functions)
      - name: Install dependencies
        working-directory: functions
        run: npm install

      # 6️⃣ Deploy Firebase Functions
      - name: Deploy to Firebase
        run: firebase deploy --only functions --project sadak-sathi-3ab73
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json
