name: Deploy Firebase (Functions + Hosting)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${GITHUB_WORKSPACE}/service-account.json"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${GITHUB_WORKSPACE}/service-account.json"

      - name: Install dependencies
        working-directory: functions
        run: npm install

      - name: Deploy Functions
        run: firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Deploy Hosting
        if: exists('firebase.json')
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }}
