name: Deploy Sadak-Sathi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Save Firebase service account
      - name: Set up Firebase Service Account
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${GITHUB_WORKSPACE}/service-account.json"

      # 4️⃣ Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5️⃣ Login to Firebase using service account
      - name: Firebase login with service account
        run: firebase login:ci --token "$(cat ${GITHUB_WORKSPACE}/service-account.json)"

      # 6️⃣ Install dependencies for functions
      - name: Install Firebase Functions dependencies
        working-directory: functions
        run: npm install

      # 7️⃣ Deploy Firebase Functions
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project sadak-sathi-3ab73

      # 8️⃣ Install frontend dependencies
      - name: Install frontend dependencies
        run: npm install

      # 9️⃣ Build frontend
      - name: Build frontend
        run: npm run build

      # 🔟 Deploy frontend to Firebase Hosting
      - name: Deploy Firebase Hosting
        run: firebase deploy --only hosting --project sadak-sathi-3ab73
