name: Firebase Multi-Hosting Deploy

on:
  push:
    branches:
      - main
      - staging
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Setup gcloud & Firebase CLI
      - name: Setup gcloud & Firebase CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: sadak-sathi-3ab73
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      # 4. Install Firebase Tools
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5. Determine hosting target based on branch
      - name: Set deployment target
        id: set-target
        run: |
          if [ "${GITHUB_REF_NAME}" == "main" ]; then
            echo "TARGET=prod-hosting" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" == "staging" ]; then
            echo "TARGET=staging-hosting" >> $GITHUB_ENV
          else
            echo "TARGET=dev-hosting" >> $GITHUB_ENV
          fi
          echo "Deploying to $TARGET"

      # 6. Deploy to Firebase Hosting
      - name: Firebase Deploy
        run: |
          firebase deploy --only hosting:$TARGET --project sadak-sathi-3ab73
