name: Deploy Firebase Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Save service account JSON from GitHub secret
      - name: Set up Service Account
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | sed 's/\\n/\n/g' > service-account.json

      # 5️⃣ Authenticate with Google Cloud
      - name: Authenticate Service Account
        run: gcloud auth activate-service-account --key-file=service-account.json

      # 6️⃣ Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 7️⃣ Deploy Firebase Functions
      - name: Deploy Functions
        run: firebase deploy --only functions --project ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
