name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Set up service account
      - name: Set up Firebase service account
        run: |
          # Save secret to file
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > service-account.json
          # Convert literal \n to real newlines
          sed -i 's/\\n/\n/g' service-account.json
          # Optional: verify JSON is valid
          python3 -c "import json; json.load(open('service-account.json'))"

      # 5. Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account.json

      # 6. Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 7. Deploy to Firebase
      - name: Deploy Firebase functions
        run: firebase deploy --only functions --project sadak-sathi-3ab73
