name: Deploy to Firebase (Automatic)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Write service account JSON from Base64 GitHub secret
      - name: Write service account JSON
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 --decode > service-account.json

      # Authenticate with Google Cloud using service account
      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account.json

      # Configure Firebase CLI to use service account (no interactive login)
      - name: Configure Firebase CLI
        run: firebase login:ci --token "$(gcloud auth print-access-token)"

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Deploy to Firebase Functions
      - name: Deploy to Firebase Functions
        run: firebase deploy --only functions --project sadak-sathi-3ab73 --token "$(gcloud auth print-access-token)"
