name: Deploy Firebase (Functions + Hosting)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Set up Service Account JSON properly
      - name: Set up Firebase Service Account
        run: |
          printf "%b" "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > service-account.json

      # 5️⃣ Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=service-account.json

      # 6️⃣ Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 7️⃣ Deploy Firebase Functions
      - name: Deploy Functions
        run: firebase deploy --only functions --project ${{ secrets.VITE_FIREBASE_PROJECT_ID }}

      # 8️⃣ Deploy Hosting if firebase.json exists
      - name: Deploy Hosting
        run: |
          if [ -f "firebase.json" ]; then
            firebase deploy --only hosting --project ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          else
            echo "No firebase.json found, skipping hosting deployment."
          fi
