name: Build & Deploy Sadak-Sathi to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Restore vite.config.ts from backup if needed
      - name: Restore vite.config.ts
        run: cp config-backup/vite.config.ts vite.config.ts || echo "No backup found, skipping"

      # 3. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 4. Install dependencies
      - name: Install dependencies
        run: npm install

      # 5. Build project
      - name: Build project
        run: npm run build

      # 6. Setup Firebase Credentials
      - name: Setup Firebase Credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > ${{ github.workspace }}/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="${{ github.workspace }}/firebase-key.json"

      # 7. Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting
