name: Build & Deploy Sadak-Sathi to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Restore vite.config.ts from backup
      - name: Restore vite.config.ts
        run: cp config-backup/vite.config.ts vite.config.ts

      # Step 3: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build the Vite project
      - name: Build project
        run: npm run build

      # Step 6: Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 7: Deploy to Firebase Hosting using GCP service account
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: sadak-sathi-3ab73
