name: Build & Deploy Sadak-Sathi to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Restore vite.config.ts from backup
      - name: Restore vite.config.ts
        run: cp config-backup/vite.config.ts vite.config.ts

      # 3️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 5️⃣ Build project
      - name: Build project
        run: npm run build

      # 6️⃣ Install Firebase CLI locally
      - name: Install Firebase CLI
        run: npm install firebase-tools

      # 7️⃣ Setup Firebase credentials from secret
      - name: Setup Firebase Credentials
        run: echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > $GITHUB_WORKSPACE/firebase-key.json

      # 8️⃣ Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-key.json
        run: npx firebase deploy --only hosting --project sadak-sathi-3ab73
