name: Build & Deploy Sadak-Sathi to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Setup Firebase Credentials
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > ${{ github.workspace }}/firebase-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="${{ github.workspace }}/firebase-key.json"

      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting --project sadak-sathi-3ab73 --non-interactive
